app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView
from core.login.views import *
from core.erp.views.project.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

from core.erp.views.dashboard.views import page_not_found404

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', include('core.login.urls')),
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    path('reports/', include('core.reports.urls')),
    path('user/', include('core.user.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

handler404 = page_not_found404

if settings.DEBUG:
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

app/core/erp/urls.py
from core.erp.views.category.views import CategoryCreateView, CategoryDeleteView, CategoryListView, CategoryUpdateView
from django.urls import path
from core.erp.views.client.views import *
from core.erp.views.dashboard.views import *
from core.erp.views.represent.views import *
from core.erp.views.product.views import *
from core.erp.views.project.views import *
from core.erp.views.servicesp.views import *
from core.erp.views.sale.views import *
from core.erp.views.position.views import *
from core.erp.views.employer.views import *
from core.erp.views.tests.views import TestView
from core.erp.views.construcction.views import *
from core.erp.views.acquisitionb.views import *
from core.erp.views.acquisitionservices.views import *
from core.erp.views.informsuni.views import *
from core.erp.views.budget.views import *
from core.erp.views.treasury.views import *
from core.erp.views.certification.views import *
from core.erp.views.perfil.views import *
from core.erp.views.perfilprod.views import *
from core.erp.views.productive.views import *
from core.erp.views.publics.views import *

app_name = 'erp'

urlpatterns = [
    # category
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # client
    path('client/list/', ClientListView.as_view(), name='client_list'),
    path('client/add/', ClientCreateView.as_view(), name='client_create'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    # product
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    # represent
    path('represent/list/', RepresentListView.as_view(), name='represent_list'),
    path('represent/add/', RepresentCreateView.as_view(), name='represent_create'),
    path('represent/update/<int:pk>/', RepresentUpdateView.as_view(), name='represent_update'),
    path('represent/delete/<int:pk>/', RepresentDeleteView.as_view(), name='represent_delete'),
    path('represent/invoice/pdf/<int:pk>/', RepresentInvoicePdfView.as_view(), name='represent_invoice_pdf'),
    # project
    path('project/list/', ProjectListView.as_view(), name='project_list'),
    path('project/add/', ProjectCreateView.as_view(), name='project_create'),
    path('project/update/<int:pk>/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/delete/<int:pk>/', ProjectDeleteView.as_view(), name='project_delete'),
    path('project/invoice/pdf/<int:pk>/', ProjectInvoicePdfView.as_view(), name='project_invoice_pdf'),
    path('project/invoicedet/pdf/<int:pk>/', ProjectdetInvoicePdfView.as_view(), name='project_invoicedet_pdf'),
    # project services profesionals
    path('servicesp/list/', ServicesProfListView.as_view(), name='servicesp_list'),
    path('servicesp/add/', ServicesProfCreateView.as_view(), name='servicesp_create'),
    path('servicesp/update/<int:pk>/', ServicesProfUpdateView.as_view(), name='servicesp_update'),
    path('servicesp/delete/<int:pk>/', ServicesProfDeleteView.as_view(), name='servicesp_delete'),
    path('servicesp/invoice/pdf/<int:pk>/', ServicesProfInvoicePdfView.as_view(), name='servicesp_invoice_pdf'),
    # project acquisition belongings
    path('acquisitionb/list/', AcquisitionbListView.as_view(), name='acquisitionb_list'),
    path('acquisitionb/add/', AcquisitionbCreateView.as_view(), name='acquisitionb_create'),
    path('acquisitionb/update/<int:pk>/', AcquisitionbUpdateView.as_view(), name='acquisitionb_update'),
    path('acquisitionb/delete/<int:pk>/', AcquisitionbDeleteView.as_view(), name='acquisitionb_delete'),
    path('acquisitionb/invoice/pdf/<int:pk>/', AcquisitionbInvoicePdfView.as_view(), name='acquisitionb_invoice_pdf'),
    # project acquisition services
    path('acquisitionservices/list/', AcquisitionServicesListView.as_view(), name='acquisitionservices_list'),
    path('acquisitionservices/add/', AcquisitionServicesCreateView.as_view(), name='acquisitionservices_create'),
    path('acquisitionservices/update/<int:pk>/', AcquisitionServicesUpdateView.as_view(), name='acquisitionservices_update'),
    path('acquisitionservices/delete/<int:pk>/', AcquisitionServicesDeleteView.as_view(), name='acquisitionservices_delete'),
    path('acquisitionservices/invoice/pdf/<int:pk>/', AcquisitionServicesInvoicePdfView.as_view(), name='acquisitionservices_invoice_pdf'),
    # project informs
    path('informsuni/list/', InformsuniListView.as_view(), name='informsuni_list'),
    path('informsuni/add/', InformsuniCreateView.as_view(), name='informsuni_create'),
    path('informsuni/update/<int:pk>/', InformsuniUpdateView.as_view(), name='informsuni_update'),
    path('informsuni/delete/<int:pk>/', InformsuniDeleteView.as_view(), name='informsuni_delete'),
    path('informsuni/invoice/pdf/<int:pk>/', InformsuniInvoicePdfView.as_view(), name='informsuni_invoice_pdf'),
    # construcction
    path('construcction/list/', ConstrucctionListView.as_view(), name='construcction_list'),
    path('construcction/add/', ConstrucctionCreateView.as_view(), name='construcction_create'),
    path('construcction/update/<int:pk>/', ConstrucctionUpdateView.as_view(), name='construcction_update'),
    path('construcction/delete/<int:pk>/', ConstrucctionDeleteView.as_view(), name='construcction_delete'),
    path('construcction/invoice/pdf/<int:pk>/', ConstrucctionInvoicePdfView.as_view(), name='construcction_invoice_pdf'),
    path('construcction/invoicedet/pdf/<int:pk>/', ConstrucctiondetInvoicePdfView.as_view(), name='construcction_invoicedet_pdf'),
    # position
    path('position/list/', PositionListView.as_view(), name='position_list'),
    path('position/add/', PositionCreateView.as_view(), name='position_create'),
    path('position/update/<int:pk>/', PositionUpdateView.as_view(), name='position_update'),
    path('position/delete/<int:pk>/', PositionDeleteView.as_view(), name='position_delete'),
    # employer
    path('employer/list/', EmployerListView.as_view(), name='employer_list'),
    path('employer/add/', EmployerCreateView.as_view(), name='employer_create'),
    path('employer/update/<int:pk>/', EmployerUpdateView.as_view(), name='employer_update'),
    path('employer/delete/<int:pk>/', EmployerDeleteView.as_view(), name='employer_delete'),
    path('employer/invoice/pdf/<int:pk>/', EmployerInvoicePdfView.as_view(), name='employer_invoice_pdf'),
    # perfil
    path('perfil/list/', PerfilListView.as_view(), name='perfil_list'),
    path('perfil/add/', PerfilCreateView.as_view(), name='perfil_create'),
    path('perfil/update/<int:pk>/', PerfilUpdateView.as_view(), name='perfil_update'),
    path('perfil/delete/<int:pk>/', PerfilDeleteView.as_view(), name='perfil_delete'),
    path('perfil/invoice/pdf/<int:pk>/', PerfilInvoicePdfView.as_view(), name='perfil_invoice_pdf'),
    # budget
    path('budget/list/', BudgetListView.as_view(), name='budget_list'),
    path('budget/add/', BudgetCreateView.as_view(), name='budget_create'),
    path('budget/update/<int:pk>/', BudgetUpdateView.as_view(), name='budget_update'),
    path('budget/delete/<int:pk>/', BudgetDeleteView.as_view(), name='budget_delete'),
    path('budget/invoice/pdf/<int:pk>/', BudgetInvoicePdfView.as_view(), name='budget_invoice_pdf'),
    # certification
    path('certification/list/', CertificationListView.as_view(), name='certification_list'),
    path('certification/add/', CertificationCreateView.as_view(), name='certification_create'),
    path('certification/update/<int:pk>/', CertificationUpdateView.as_view(), name='certification_update'),
    path('certification/delete/<int:pk>/', CertificationDeleteView.as_view(), name='certification_delete'),
    path('certification/invoice/pdf/<int:pk>/', CertificationInvoicePdfView.as_view(), name='certification_invoice_pdf'),
    # treasury
    path('treasury/list/', TreasuryListView.as_view(), name='treasury_list'),
    path('treasury/add/', TreasuryCreateView.as_view(), name='treasury_create'),
    path('treasury/update/<int:pk>/', TreasuryUpdateView.as_view(), name='treasury_update'),
    path('treasury/delete/<int:pk>/', TreasuryDeleteView.as_view(), name='treasury_delete'),
    path('treasury/invoice/pdf/<int:pk>/', TreasuryInvoicePdfView.as_view(), name='treasury_invoice_pdf'),
    # productive
    path('productive/list/', ProductiveListView.as_view(), name='productive_list'),
    path('productive/add/', ProductiveCreateView.as_view(), name='productive_create'),
    path('productive/update/<int:pk>/', ProductiveUpdateView.as_view(), name='productive_update'),
    path('productive/delete/<int:pk>/', ProductiveDeleteView.as_view(), name='productive_delete'),
    path('productive/invoice/pdf/<int:pk>/', ProductiveInvoicePdfView.as_view(), name='productive_invoice_pdf'),
    path('productive/invoicedet/pdf/<int:pk>/', ProductivedetInvoicePdfView.as_view(), name='productive_invoicedet_pdf'),
    # perfilprod
    path('perfilprod/list/', PerfilprodListView.as_view(), name='perfilprod_list'),
    path('perfilprod/add/', PerfilprodCreateView.as_view(), name='perfilprod_create'),
    path('perfilprod/update/<int:pk>/', PerfilprodUpdateView.as_view(), name='perfilprod_update'),
    path('perfilprod/delete/<int:pk>/', PerfilprodDeleteView.as_view(), name='perfilprod_delete'),
    path('perfilprod/invoice/pdf/<int:pk>/', PerfilprodInvoicePdfView.as_view(), name='perfilprod_invoice_pdf'),
    # publics

app/core/erp/views/dashboard/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, DecimalField
from django.db.models.functions import Coalesce
from django.http import JsonResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from core.erp.models import Sale, Product, DetSale

from random import randint


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    # def get(self, request, *args, **kwargs):
    #     request.user.get_group_session()
    #     return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'get_graph_sales_year_month':
                data = {
                    'name': 'Porcentaje de venta',
                    'showInLegend': False,
                    'colorByPoint': True,
                    'data': self.get_graph_sales_year_month()
                }
            elif action == 'get_graph_sales_products_year_month':
                data = {
                    'name': 'Porcentaje',
                    'colorByPoint': True,
                    'data': self.get_graph_sales_products_year_month(),
                }
            elif action == 'get_graph_online':
                data = {'y': randint(1, 100)}
                print(data)
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_graph_sales_year_month(self):
        data = []
        try:
            year = datetime.now().year
            for m in range(1, 13):
                total = Sale.objects.filter(date_joined__year=year, date_joined__month=m).aggregate(
                    r=Coalesce(Sum('total'), 0, output_field=DecimalField())).get('r')
                    # r=Coalesce(Sum('total'), 0)).get('r')
                data.append(float(total))
        except:
            pass
        return data

    def get_graph_sales_products_year_month(self):
        data = []
        year = datetime.now().year
        month = datetime.now().month
        try:
            for p in Product.objects.all():
                total = DetSale.objects.filter(sale__date_joined__year=year, sale__date_joined__month=month,
                                        prod_id=p.id).aggregate(
                    r=Coalesce(Sum('subtotal'), 0, output_field=DecimalField())).get('r')
                    # r=Coalesce(Sum('subtotal'), 0)).get('r')
                if total > 0:
                    data.append({
                        'name': p.name,
                        'y': float(total)
                    })
        except:
            pass
        return data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'Panel de administrador'
        context['graph_sales_year_month'] = self.get_graph_sales_year_month()
        return context


def page_not_found404(request, exception):
    return render(request, '404.html')

app/templates/dashboard.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
    <script src="{% static 'lib/highcharts-8.1.2/highcharts.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/exporting.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/export-data.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/accessibility.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div id="container"></div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-12">
                <div id="container-pie"></div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-12">
                <div id="container-online"></div>
            </div>
        </div>
        <br>
    </div>
    <script type="application/javascript">
        var graphcolumn = Highcharts.chart('container', {
            chart: {
                type: 'column'
            },
            title: {
                text: 'Reporte de ventas del año 2022'
            },
            subtitle: {
                text: 'Reporte de columnas'
            },
            xAxis: {
                categories: [
                    'Enero',
                    'Febrero',
                    'Marzo',
                    'Abril',
                    'Mayo',
                    'Junio',
                    'Julio',
                    'Agosto',
                    'Septiembre',
                    'Octubre',
                    'Noviembre',
                    'Diciembre'
                ],
                crosshair: true
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Valores $'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                    '<td style="padding:0"><b>{point.y:.1f} $</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
        });

        var graphpie = Highcharts.chart('container-pie', {
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie'
            },
            title: {
                text: 'Porcentaje de venta de productos por el mes de Junio del año 2020'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            accessibility: {
                point: {
                    valueSuffix: '%'
                }
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                    }
                }
            },
        });

        /*Highcharts.chart('container-online', {
            chart: {
                type: 'spline',
                animation: Highcharts.svg, // don't animate in old IE
                marginRight: 10,
                events: {
                    load: function () {
                        var series = this.series[0];
                        setInterval(function () {
                            $.ajax({
                                url: window.location.pathname, //window.location.pathname
                                type: 'POST',
                                data: {
                                    'action': 'get_graph_online'
                                },
                                dataType: 'json',
                            }).done(function (data) {
                                if (!data.hasOwnProperty('error')) {
                                    var x = (new Date()).getTime();
                                    series.addPoint([x, data.y], true, true);
                                    return false;
                                }
                                message_error(data.error);
                            }).fail(function (jqXHR, textStatus, errorThrown) {
                                alert(textStatus + ': ' + errorThrown);
                            }).always(function (data) {

                            });
                        }, 1000);
                    }
                }
            },

            time: {
                useUTC: false
            },

            title: {
                text: 'Live random data'
            },

            accessibility: {
                announceNewData: {
                    enabled: true,
                    minAnnounceInterval: 15000,
                    announcementFormatter: function (allSeries, newSeries, newPoint) {
                        if (newPoint) {
                            return 'New point added. Value: ' + newPoint.y;
                        }
                        return false;
                    }
                }
            },

            xAxis: {
                type: 'datetime',
                tickPixelInterval: 150
            },

            yAxis: {
                title: {
                    text: 'Value'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },

            tooltip: {
                headerFormat: '<b>{series.name}</b><br/>',
                pointFormat: '{point.x:%Y-%m-%d %H:%M:%S}<br/>{point.y:.2f}'
            },

            legend: {
                enabled: false
            },

            exporting: {
                enabled: false
            },

            series: [{
                name: 'Random data',
                data: (function () {
                    // generate an array of random data
                    var data = [],
                        time = (new Date()).getTime(),
                        i;

                    for (i = -19; i <= 0; i += 1) {
                        data.push({
                            x: time + i * 1000,
                            y: Math.random()
                        });
                    }
                    return data;
                }())
            }]
        });*/

        function get_graph_sales_year_month() {
            $.ajax({
                url: window.location.pathname, //window.location.pathname
                type: 'POST',
                data: {
                    'action': 'get_graph_sales_year_month'
                },
                dataType: 'json',
            }).done(function (data) {
                if (!data.hasOwnProperty('error')) {
                    graphcolumn.addSeries(data);
                    return false;
                }
                message_error(data.error);
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function (data) {

            });
        }

        function get_graph_sales_products_year_month() {
            $.ajax({
                url: window.location.pathname, //window.location.pathname
                type: 'POST',
                data: {
                    'action': 'get_graph_sales_products_year_month'
                },
                dataType: 'json',
            }).done(function (data) {
                if (!data.hasOwnProperty('error')) {
                    graphpie.addSeries(data);
                    return false;
                }
                message_error(data.error);
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function (data) {

            });
        }

        $(function () {

            get_graph_sales_year_month();

            get_graph_sales_products_year_month();

        });
    </script>
{% endblock %}

app/templates/dashboard1.html
{% extends 'layout.html' %}

app/templates/delete.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action=".">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="alert alert-danger alert-dismissible">
                    <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                    ¿Estas seguro de eliminar el registro N°{{ object.id }}?
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Si, aceptar
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
        <!-- <p>{{ list_url }}</p>-->
    </form>
    <script>
        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de eliminar el siguiente registro?', parameters, function () {
                Swal.fire({
                    title: 'Alerta',
                    text: 'Registro eliminado correctamente',
                    icon: 'success',
                    time: 2500
                }).then((result) => {
                    location.href = "{{ list_url }}";
                })
                
            });
        });
    </script>
{% endblock %}

app/templates/footer.html
<!-- Main Footer -->
<footer class="main-footer text-center">
    <strong>Copyright &copy; 2020-2021 <a href="https://adminlte.io">ArcaCorp</a>.</strong><br>
    Todos los derechos reservados.
</footer>

app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" href="{% static 'img/empty.png' %}" type="image/png"/>
    <title>{{ title }}</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
    <!-- Sweetalert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- Jquery Confirm -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- My css -->
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <!-- Functions -->
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- Editor Text -->
    <script src="https://cdn.ckeditor.com/4.16.2/full/ckeditor.js"></script>
    <!-- Ckeditor -->
    <script src="{% static 'lib/ckeditor/full/ckeditor.js' %}"></script>
    <!-- Time -->
    <!-- <script src="{% static 'lib/moment-2.25.3/moment-with-locales.js' %}"></script>
    <script src="{% static 'lib/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.js' %}"></script>
    <link href="{% static 'lib/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet"/> -->
    
    <!-- Block head -->
    
    {% block head %}

    {% endblock %}
</head>
{% block body %}

{% endblock %}
</html>

app/templates/layout.html
{% extends 'vtc/body.html' %}

app/templates/list.html
{% extends 'layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet"
        href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

    {% block head_list %}

    {% endblock %}

{% endblock %}

{% block content %}
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                {{ title }}
            </h3>
        </div>
        <div class="card-body">
            <table class="table table-bordered" id="data">
                <thead>
                    {% block columns %}
                    
                    {% endblock %}
                </thead>
                <tbody>
                    {% block rows %}
                    
                    {% endblock %}
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {% block buttons_list %}
                <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">
                    <i class="fas fa-plus"></i> Nuevo registro
                </a>
                <a href="{{ list_url }}" class="btn btn-success btn-flat">
                    <i class="fas fa-sync"></i> Actualizar
                </a>
            {% endblock %}

{% block modal %}
  
{% endblock modal %}

        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false
            });

            $('.btnTest').on('click', function () {
                $.ajax({
                    url: '{% url 'erp:category_list' %}',
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function (data) {
                    console.log(data);
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                }).always(function (data) {

                });
            });
        });
    </script>
{% endblock %}